2024-12-08 07:08:14.455175: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-08 07:08:14.461185: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-08 07:08:14.480800: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1733641694.521311   12900 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1733641694.530685   12900 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-08 07:08:14.563261: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/tfdata/producer_consumer_gpu.py", line 1, in <module>
    import tensorflow as tf
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/tensorflow/__init__.py", line 467, in <module>
    importlib.import_module("keras.src.optimizers")
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/__init__.py", line 2, in <module>
    from keras.api import DTypePolicy
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/activations/__init__.py", line 30, in <module>
    from keras.src.saving import object_registration
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/saving/__init__.py", line 7, in <module>
    from keras.src.saving.saving_api import load_model
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 7, in <module>
    from keras.src.legacy.saving import legacy_h5_format
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 13, in <module>
    from keras.src.legacy.saving import saving_utils
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/legacy/saving/saving_utils.py", line 10, in <module>
    from keras.src import models
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/__init__.py", line 1, in <module>
    from keras.src.models.functional import Functional
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/functional.py", line 16, in <module>
    from keras.src.models.model import Model
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/model.py", line 12, in <module>
    from keras.src.trainers import trainer as base_trainer
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/trainer.py", line 14, in <module>
    from keras.src.trainers.data_adapters import data_adapter_utils
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/__init__.py", line 4, in <module>
    from keras.src.trainers.data_adapters import array_data_adapter
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py", line 7, in <module>
    from keras.src.trainers.data_adapters import array_slicing
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/array_slicing.py", line 12, in <module>
    import pandas
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/tfdata/producer_consumer_gpu.py", line 1, in <module>
    import tensorflow as tf
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/tensorflow/__init__.py", line 467, in <module>
    importlib.import_module("keras.src.optimizers")
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/__init__.py", line 2, in <module>
    from keras.api import DTypePolicy
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/activations/__init__.py", line 30, in <module>
    from keras.src.saving import object_registration
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/saving/__init__.py", line 7, in <module>
    from keras.src.saving.saving_api import load_model
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/saving/saving_api.py", line 7, in <module>
    from keras.src.legacy.saving import legacy_h5_format
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 13, in <module>
    from keras.src.legacy.saving import saving_utils
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/legacy/saving/saving_utils.py", line 10, in <module>
    from keras.src import models
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/__init__.py", line 1, in <module>
    from keras.src.models.functional import Functional
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/functional.py", line 16, in <module>
    from keras.src.models.model import Model
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/models/model.py", line 12, in <module>
    from keras.src.trainers import trainer as base_trainer
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/trainer.py", line 14, in <module>
    from keras.src.trainers.data_adapters import data_adapter_utils
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/__init__.py", line 4, in <module>
    from keras.src.trainers.data_adapters import array_data_adapter
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/array_data_adapter.py", line 7, in <module>
    from keras.src.trainers.data_adapters import array_slicing
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/keras/src/trainers/data_adapters/array_slicing.py", line 12, in <module>
    import pandas
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
  Process Memory Usage: 210.96 MB
  Total Memory: 7820.91 MB
  Used Memory: 3081.55 MB (43.50%)
  Available Memory: 4422.62 MB

2024-12-08 07:08:17.855230: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
  Process Memory Usage: 211.46 MB
  Total Memory: 7820.91 MB
  Used Memory: 3110.49 MB (43.80%)
  Available Memory: 4393.68 MB

  Process Memory Usage: 211.46 MB
  Total Memory: 7820.91 MB
  Used Memory: 3240.04 MB (45.50%)
  Available Memory: 4264.14 MB

  Process Memory Usage: 211.46 MB
  Total Memory: 7820.91 MB
  Used Memory: 3820.41 MB (52.90%)
  Available Memory: 3683.77 MB

  Process Memory Usage: 211.46 MB
  Total Memory: 7820.91 MB
  Used Memory: 3668.89 MB (51.00%)
  Available Memory: 3835.29 MB

Memory tracking interrupted, shutting down.
Traceback (most recent call last):
  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/tfdata/producer_consumer_gpu.py", line 125, in <module>
    bench(args.mem_limit)
  File "/home/ubuntu/ray-data-eval/ray_data_eval/microbenchmarks/tfdata/producer_consumer_gpu.py", line 103, in bench
    for row in ds:
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 826, in __next__
    return self._next_internal()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 776, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/ray-data/lib/python3.11/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3081, in iterator_get_next
    _result = pywrap_tfe.TFE_Py_FastPathExecute(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
